export type Revelation = "meccan" | "medinan";

export type SurahMeta = {
  number: number;
  nameAr: string;
  nameLatin: string;
  meaning: string;
  ayahCount: number;
  juz: number; // starting juz
  revelation: Revelation;
};

export const SURAHS: SurahMeta[] = [
  { number: 1, nameAr: "الفاتحة", nameLatin: "Al-Fatihah", meaning: "The Opening", ayahCount: 7, juz: 1, revelation: "meccan" },
  { number: 2, nameAr: "البقرة", nameLatin: "Al-Baqarah", meaning: "The Cow", ayahCount: 286, juz: 1, revelation: "medinan" },
  { number: 3, nameAr: "آل عمران", nameLatin: "Aal-e-Imran", meaning: "The Family of Imran", ayahCount: 200, juz: 3, revelation: "medinan" },
  { number: 4, nameAr: "النساء", nameLatin: "An-Nisa", meaning: "The Women", ayahCount: 176, juz: 4, revelation: "medinan" },
  { number: 5, nameAr: "المائدة", nameLatin: "Al-Ma'idah", meaning: "The Table Spread", ayahCount: 120, juz: 6, revelation: "medinan" },
  { number: 6, nameAr: "الأنعام", nameLatin: "Al-An'am", meaning: "The Cattle", ayahCount: 165, juz: 7, revelation: "meccan" },
  { number: 7, nameAr: "الأعراف", nameLatin: "Al-A'raf", meaning: "The Heights", ayahCount: 206, juz: 8, revelation: "meccan" },
  { number: 8, nameAr: "الأنفال", nameLatin: "Al-Anfal", meaning: "The Spoils of War", ayahCount: 75, juz: 9, revelation: "medinan" },
  { number: 9, nameAr: "التوبة", nameLatin: "At-Tawbah", meaning: "The Repentance", ayahCount: 129, juz: 10, revelation: "medinan" },
  { number: 10, nameAr: "يونس", nameLatin: "Yunus", meaning: "Jonah", ayahCount: 109, juz: 11, revelation: "meccan" },
  { number: 11, nameAr: "هود", nameLatin: "Hud", meaning: "Hud", ayahCount: 123, juz: 11, revelation: "meccan" },
  { number: 12, nameAr: "يوسف", nameLatin: "Yusuf", meaning: "Joseph", ayahCount: 111, juz: 12, revelation: "meccan" },
  { number: 13, nameAr: "الرعد", nameLatin: "Ar-Ra'd", meaning: "The Thunder", ayahCount: 43, juz: 13, revelation: "medinan" },
  { number: 14, nameAr: "إبراهيم", nameLatin: "Ibrahim", meaning: "Abraham", ayahCount: 52, juz: 13, revelation: "meccan" },
  { number: 15, nameAr: "الحجر", nameLatin: "Al-Hijr", meaning: "The Rocky Tract", ayahCount: 99, juz: 14, revelation: "meccan" },
  { number: 16, nameAr: "النحل", nameLatin: "An-Nahl", meaning: "The Bee", ayahCount: 128, juz: 14, revelation: "meccan" },
  { number: 17, nameAr: "الإسراء", nameLatin: "Al-Isra", meaning: "The Night Journey", ayahCount: 111, juz: 15, revelation: "meccan" },
  { number: 18, nameAr: "الكهف", nameLatin: "Al-Kahf", meaning: "The Cave", ayahCount: 110, juz: 15, revelation: "meccan" },
  { number: 19, nameAr: "مريم", nameLatin: "Maryam", meaning: "Mary", ayahCount: 98, juz: 16, revelation: "meccan" },
  { number: 20, nameAr: "طه", nameLatin: "Taha", meaning: "Ta-Ha", ayahCount: 135, juz: 16, revelation: "meccan" },
  { number: 21, nameAr: "الأنبياء", nameLatin: "Al-Anbiya", meaning: "The Prophets", ayahCount: 112, juz: 17, revelation: "meccan" },
  { number: 22, nameAr: "الحج", nameLatin: "Al-Hajj", meaning: "The Pilgrimage", ayahCount: 78, juz: 17, revelation: "medinan" },
  { number: 23, nameAr: "المؤمنون", nameLatin: "Al-Mu'minun", meaning: "The Believers", ayahCount: 118, juz: 18, revelation: "meccan" },
  { number: 24, nameAr: "النور", nameLatin: "An-Nur", meaning: "The Light", ayahCount: 64, juz: 18, revelation: "medinan" },
  { number: 25, nameAr: "الفرقان", nameLatin: "Al-Furqan", meaning: "The Criterion", ayahCount: 77, juz: 18, revelation: "meccan" },
  { number: 26, nameAr: "الشعراء", nameLatin: "Ash-Shu'ara", meaning: "The Poets", ayahCount: 227, juz: 19, revelation: "meccan" },
  { number: 27, nameAr: "النمل", nameLatin: "An-Naml", meaning: "The Ant", ayahCount: 93, juz: 19, revelation: "meccan" },
  { number: 28, nameAr: "القصص", nameLatin: "Al-Qasas", meaning: "The Stories", ayahCount: 88, juz: 20, revelation: "meccan" },
  { number: 29, nameAr: "العنكبوت", nameLatin: "Al-Ankabut", meaning: "The Spider", ayahCount: 69, juz: 20, revelation: "meccan" },
  { number: 30, nameAr: "الروم", nameLatin: "Ar-Rum", meaning: "The Romans", ayahCount: 60, juz: 21, revelation: "meccan" },
  { number: 31, nameAr: "لقمان", nameLatin: "Luqman", meaning: "Luqman", ayahCount: 34, juz: 21, revelation: "meccan" },
  { number: 32, nameAr: "السجدة", nameLatin: "As-Sajdah", meaning: "The Prostration", ayahCount: 30, juz: 21, revelation: "meccan" },
  { number: 33, nameAr: "الأحزاب", nameLatin: "Al-Ahzab", meaning: "The Combined Forces", ayahCount: 73, juz: 21, revelation: "medinan" },
  { number: 34, nameAr: "سبأ", nameLatin: "Saba", meaning: "Sheba", ayahCount: 54, juz: 22, revelation: "meccan" },
  { number: 35, nameAr: "فاطر", nameLatin: "Fatir", meaning: "Originator", ayahCount: 45, juz: 22, revelation: "meccan" },
  { number: 36, nameAr: "يس", nameLatin: "Ya-Sin", meaning: "Ya Sin", ayahCount: 83, juz: 22, revelation: "meccan" },
  { number: 37, nameAr: "الصافات", nameLatin: "As-Saffat", meaning: "Those who set the Ranks", ayahCount: 182, juz: 23, revelation: "meccan" },
  { number: 38, nameAr: "ص", nameLatin: "Sad", meaning: "The Letter Sad", ayahCount: 88, juz: 23, revelation: "meccan" },
  { number: 39, nameAr: "الزمر", nameLatin: "Az-Zumar", meaning: "The Troops", ayahCount: 75, juz: 23, revelation: "meccan" },
  { number: 40, nameAr: "غافر", nameLatin: "Ghafir", meaning: "The Forgiver", ayahCount: 85, juz: 24, revelation: "meccan" },
  { number: 41, nameAr: "فصلت", nameLatin: "Fussilat", meaning: "Explained in Detail", ayahCount: 54, juz: 24, revelation: "meccan" },
  { number: 42, nameAr: "الشورى", nameLatin: "Ash-Shura", meaning: "The Consultation", ayahCount: 53, juz: 25, revelation: "meccan" },
  { number: 43, nameAr: "الزخرف", nameLatin: "Az-Zukhruf", meaning: "The Ornaments of Gold", ayahCount: 89, juz: 25, revelation: "meccan" },
  { number: 44, nameAr: "الدخان", nameLatin: "Ad-Dukhan", meaning: "The Smoke", ayahCount: 59, juz: 25, revelation: "meccan" },
  { number: 45, nameAr: "الجاثية", nameLatin: "Al-Jathiyah", meaning: "The Crouching", ayahCount: 37, juz: 25, revelation: "meccan" },
  { number: 46, nameAr: "الأحقاف", nameLatin: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills", ayahCount: 35, juz: 26, revelation: "meccan" },
  { number: 47, nameAr: "محمد", nameLatin: "Muhammad", meaning: "Muhammad", ayahCount: 38, juz: 26, revelation: "medinan" },
  { number: 48, nameAr: "الفتح", nameLatin: "Al-Fath", meaning: "The Victory", ayahCount: 29, juz: 26, revelation: "medinan" },
  { number: 49, nameAr: "الحجرات", nameLatin: "Al-Hujurat", meaning: "The Rooms", ayahCount: 18, juz: 26, revelation: "medinan" },
  { number: 50, nameAr: "ق", nameLatin: "Qaf", meaning: "The Letter Qaf", ayahCount: 45, juz: 26, revelation: "meccan" },
  { number: 51, nameAr: "الذاريات", nameLatin: "Adh-Dhariyat", meaning: "The Winnowing Winds", ayahCount: 60, juz: 26, revelation: "meccan" },
  { number: 52, nameAr: "الطور", nameLatin: "At-Tur", meaning: "The Mount", ayahCount: 49, juz: 27, revelation: "meccan" },
  { number: 53, nameAr: "النجم", nameLatin: "An-Najm", meaning: "The Star", ayahCount: 62, juz: 27, revelation: "meccan" },
  { number: 54, nameAr: "القمر", nameLatin: "Al-Qamar", meaning: "The Moon", ayahCount: 55, juz: 27, revelation: "meccan" },
  { number: 55, nameAr: "الرحمن", nameLatin: "Ar-Rahman", meaning: "The Beneficent", ayahCount: 78, juz: 27, revelation: "medinan" },
  { number: 56, nameAr: "الواقعة", nameLatin: "Al-Waqi'ah", meaning: "The Inevitable", ayahCount: 96, juz: 27, revelation: "meccan" },
  { number: 57, nameAr: "الحديد", nameLatin: "Al-Hadid", meaning: "The Iron", ayahCount: 29, juz: 27, revelation: "medinan" },
  { number: 58, nameAr: "المجادلة", nameLatin: "Al-Mujadila", meaning: "The Pleading Woman", ayahCount: 22, juz: 28, revelation: "medinan" },
  { number: 59, nameAr: "الحشر", nameLatin: "Al-Hashr", meaning: "The Exile", ayahCount: 24, juz: 28, revelation: "medinan" },
  { number: 60, nameAr: "الممتحنة", nameLatin: "Al-Mumtahanah", meaning: "She that is to be examined", ayahCount: 13, juz: 28, revelation: "medinan" },
  { number: 61, nameAr: "الصف", nameLatin: "As-Saff", meaning: "The Ranks", ayahCount: 14, juz: 28, revelation: "medinan" },
  { number: 62, nameAr: "الجمعة", nameLatin: "Al-Jumu'ah", meaning: "The Congregation, Friday", ayahCount: 11, juz: 28, revelation: "medinan" },
  { number: 63, nameAr: "المنافقون", nameLatin: "Al-Munafiqun", meaning: "The Hypocrites", ayahCount: 11, juz: 28, revelation: "medinan" },
  { number: 64, nameAr: "التغابن", nameLatin: "At-Taghabun", meaning: "The Mutual Disillusion", ayahCount: 18, juz: 28, revelation: "medinan" },
  { number: 65, nameAr: "الطلاق", nameLatin: "At-Talaq", meaning: "The Divorce", ayahCount: 12, juz: 28, revelation: "medinan" },
  { number: 66, nameAr: "التحريم", nameLatin: "At-Tahrim", meaning: "The Prohibition", ayahCount: 12, juz: 28, revelation: "medinan" },
  { number: 67, nameAr: "الملك", nameLatin: "Al-Mulk", meaning: "The Sovereignty", ayahCount: 30, juz: 29, revelation: "meccan" },
  { number: 68, nameAr: "القلم", nameLatin: "Al-Qalam", meaning: "The Pen", ayahCount: 52, juz: 29, revelation: "meccan" },
  { number: 69, nameAr: "الحاقة", nameLatin: "Al-Haqqah", meaning: "The Reality", ayahCount: 52, juz: 29, revelation: "meccan" },
  { number: 70, nameAr: "المعارج", nameLatin: "Al-Ma'arij", meaning: "The Ascending Stairways", ayahCount: 44, juz: 29, revelation: "meccan" },
  { number: 71, nameAr: "نوح", nameLatin: "Nuh", meaning: "Noah", ayahCount: 28, juz: 29, revelation: "meccan" },
  { number: 72, nameAr: "الجن", nameLatin: "Al-Jinn", meaning: "The Jinn", ayahCount: 28, juz: 29, revelation: "meccan" },
  { number: 73, nameAr: "المزمل", nameLatin: "Al-Muzzammil", meaning: "The Enshrouded One", ayahCount: 20, juz: 29, revelation: "meccan" },
  { number: 74, nameAr: "المدثر", nameLatin: "Al-Muddaththir", meaning: "The Cloaked One", ayahCount: 56, juz: 29, revelation: "meccan" },
  { number: 75, nameAr: "القيامة", nameLatin: "Al-Qiyamah", meaning: "The Resurrection", ayahCount: 40, juz: 29, revelation: "meccan" },
  { number: 76, nameAr: "الإنسان", nameLatin: "Al-Insan", meaning: "The Man", ayahCount: 31, juz: 29, revelation: "medinan" },
  { number: 77, nameAr: "المرسلات", nameLatin: "Al-Mursalat", meaning: "The Emissaries", ayahCount: 50, juz: 29, revelation: "meccan" },
  { number: 78, nameAr: "النبأ", nameLatin: "An-Naba", meaning: "The Tidings", ayahCount: 40, juz: 30, revelation: "meccan" },
  { number: 79, nameAr: "النازعات", nameLatin: "An-Nazi'at", meaning: "Those who drag forth", ayahCount: 46, juz: 30, revelation: "meccan" },
  { number: 80, nameAr: "عبس", nameLatin: "Abasa", meaning: "He Frowned", ayahCount: 42, juz: 30, revelation: "meccan" },
  { number: 81, nameAr: "التكوير", nameLatin: "At-Takwir", meaning: "The Overthrowing", ayahCount: 29, juz: 30, revelation: "meccan" },
  { number: 82, nameAr: "الانفطار", nameLatin: "Al-Infitar", meaning: "The Cleaving", ayahCount: 19, juz: 30, revelation: "meccan" },
  { number: 83, nameAr: "المطففين", nameLatin: "Al-Mutaffifin", meaning: "The Defrauding", ayahCount: 36, juz: 30, revelation: "meccan" },
  { number: 84, nameAr: "الانشقاق", nameLatin: "Al-Inshiqaq", meaning: "The Sundering", ayahCount: 25, juz: 30, revelation: "meccan" },
  { number: 85, nameAr: "البروج", nameLatin: "Al-Buruj", meaning: "The Mansions of the Stars", ayahCount: 22, juz: 30, revelation: "meccan" },
  { number: 86, nameAr: "الطارق", nameLatin: "At-Tariq", meaning: "The Morning Star", ayahCount: 17, juz: 30, revelation: "meccan" },
  { number: 87, nameAr: "الأعلى", nameLatin: "Al-A'la", meaning: "The Most High", ayahCount: 19, juz: 30, revelation: "meccan" },
  { number: 88, nameAr: "الغاشية", nameLatin: "Al-Ghashiyah", meaning: "The Overwhelming", ayahCount: 26, juz: 30, revelation: "meccan" },
  { number: 89, nameAr: "الفجر", nameLatin: "Al-Fajr", meaning: "The Dawn", ayahCount: 30, juz: 30, revelation: "meccan" },
  { number: 90, nameAr: "البلد", nameLatin: "Al-Balad", meaning: "The City", ayahCount: 20, juz: 30, revelation: "meccan" },
  { number: 91, nameAr: "الشمس", nameLatin: "Ash-Shams", meaning: "The Sun", ayahCount: 15, juz: 30, revelation: "meccan" },
  { number: 92, nameAr: "الليل", nameLatin: "Al-Layl", meaning: "The Night", ayahCount: 21, juz: 30, revelation: "meccan" },
  { number: 93, nameAr: "الضحى", nameLatin: "Ad-Duha", meaning: "The Morning Hours", ayahCount: 11, juz: 30, revelation: "meccan" },
  { number: 94, nameAr: "الشرح", nameLatin: "Ash-Sharh", meaning: "The Relief", ayahCount: 8, juz: 30, revelation: "meccan" },
  { number: 95, nameAr: "التين", nameLatin: "At-Tin", meaning: "The Fig", ayahCount: 8, juz: 30, revelation: "meccan" },
  { number: 96, nameAr: "العلق", nameLatin: "Al-Alaq", meaning: "The Clot", ayahCount: 19, juz: 30, revelation: "meccan" },
  { number: 97, nameAr: "القدر", nameLatin: "Al-Qadr", meaning: "The Power", ayahCount: 5, juz: 30, revelation: "meccan" },
  { number: 98, nameAr: "البينة", nameLatin: "Al-Bayyinah", meaning: "The Clear Proof", ayahCount: 8, juz: 30, revelation: "medinan" },
  { number: 99, nameAr: "الزلزلة", nameLatin: "Az-Zalzalah", meaning: "The Earthquake", ayahCount: 8, juz: 30, revelation: "medinan" },
  { number: 100, nameAr: "العاديات", nameLatin: "Al-Adiyat", meaning: "The Courser", ayahCount: 11, juz: 30, revelation: "meccan" },
  { number: 101, nameAr: "القارعة", nameLatin: "Al-Qari'ah", meaning: "The Calamity", ayahCount: 11, juz: 30, revelation: "meccan" },
  { number: 102, nameAr: "التكاثر", nameLatin: "At-Takathur", meaning: "The Rivalry in world increase", ayahCount: 8, juz: 30, revelation: "meccan" },
  { number: 103, nameAr: "العصر", nameLatin: "Al-Asr", meaning: "The Declining Day", ayahCount: 3, juz: 30, revelation: "meccan" },
  { number: 104, nameAr: "الهمزة", nameLatin: "Al-Humazah", meaning: "The Traducer", ayahCount: 9, juz: 30, revelation: "meccan" },
  { number: 105, nameAr: "الفيل", nameLatin: "Al-Fil", meaning: "The Elephant", ayahCount: 5, juz: 30, revelation: "meccan" },
  { number: 106, nameAr: "قريش", nameLatin: "Quraysh", meaning: "Quraysh", ayahCount: 4, juz: 30, revelation: "meccan" },
  { number: 107, nameAr: "الماعون", nameLatin: "Al-Ma'un", meaning: "The Small Kindnesses", ayahCount: 7, juz: 30, revelation: "meccan" },
  { number: 108, nameAr: "الكوثر", nameLatin: "Al-Kawthar", meaning: "The Abundance", ayahCount: 3, juz: 30, revelation: "meccan" },
  { number: 109, nameAr: "الكافرون", nameLatin: "Al-Kafirun", meaning: "The Disbelievers", ayahCount: 6, juz: 30, revelation: "meccan" },
  { number: 110, nameAr: "النصر", nameLatin: "An-Nasr", meaning: "The Divine Support", ayahCount: 3, juz: 30, revelation: "medinan" },
  { number: 111, nameAr: "المسد", nameLatin: "Al-Masad", meaning: "The Palm Fiber", ayahCount: 5, juz: 30, revelation: "meccan" },
  { number: 112, nameAr: "الإخلاص", nameLatin: "Al-Ikhlas", meaning: "The Sincerity", ayahCount: 4, juz: 30, revelation: "meccan" },
  { number: 113, nameAr: "الفلق", nameLatin: "Al-Falaq", meaning: "The Daybreak", ayahCount: 5, juz: 30, revelation: "meccan" },
  { number: 114, nameAr: "الناس", nameLatin: "An-Nas", meaning: "Mankind", ayahCount: 6, juz: 30, revelation: "meccan" },
];

export const TOTAL_AYAHS = SURAHS.reduce((sum, s) => sum + s.ayahCount, 0);

export function getSurah(n: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.number === n);
}

export const JUZ_NAMES: Record<number, string> = {
  30: "جزء عمّ",
  29: "جزء تبارك",
  1: "جزء آلم",
};
